AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  
  SAM Template for cloud-resume-backend

Globals:
  Api:
    OpenApiVersion: 3.0.1

Resources:

  MyResumeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyResumeApi
      StageName: prod
      Cors: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: ./swagger.yaml

  ResumeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: lambda_function.py
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - logs:CreateLogGroup
            Resource: 'arn:aws:dynamodb:us-east-2:276968177400:table/visitorcount'
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:eu-east-2:276968177400:*'
          - Effect: Allow
			      Action: 
              - logs:CreateLogGroup
			      Resource: "*"

  ResumeDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: 'siteUrl'
          AttributeType: 'S'
      KeySchema:
        - 
          AttributeName: 'siteUrl'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: 'visitorcount'           

Outputs:

  ResumeApi:
    Description: "API Gateway endpoint URL for Prod stage for Cloud Resume function"
    Value: !Sub "https://${MyResumeApi}.execute-api.${AWS::Region}.amazonaws.com/prod/count"
  ResumeFunction:
    Description: "Cloud Resume Lambda Function ARN"
    Value: !GetAtt ResumeFunction.Arn
  ResumeFunctionIamRole:
    Description: "Implicit IAM Role created for Cloud Resume function"
    Value: !GetAtt ResumeFunctionRole.Arn
  ResumeDBTable:
    Description: "DynamoDB table to store the visitor count"
    Value: !GetAtt ResumeDBTable.Arn
