AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  
  SAM Template for cloud-resume-backend

Globals:
  Api:
    OpenApiVersion: 3.0.1

Resources:

  ResumeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ResumeApi
      StageName: prod
      Cors: "'*'"

  ResumeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::276968177400:role/ResumeLambdaRole
      CodeUri: lambda_function.py
      Policies:
        - ResumeLambdaPolicy
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource: 'arn:aws:dynamodb:us-east-2:276968177400:table/visitorcount'
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:us-east-2:276968177400:*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
            Resource: '*'
      Events: 
        ApiEvent:
          Type: Api
          Properties:
            Path: /count
            Method: get
            RestApiId:
              Ref: ResumeApi
  
  ResumeDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: 'siteUrl'
          AttributeType: 'S'
      KeySchema:
        - 
          AttributeName: 'siteUrl'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName: 'visitorcount'           

Outputs:
  ResumeApi:
    Description: "API Gateway endpoint URL for Prod stage for Cloud Resume function"
    Value: !Sub "https://${ResumeApi}.execute-api.${AWS::Region}.amazonaws.com/prod/count"
  ResumeFunction:
    Description: "Cloud Resume Lambda Function ARN"
    Value: !GetAtt ResumeFunction.Arn
  ResumeDBTable:
    Description: "DynamoDB table to store the visitor count"
    Value: !GetAtt ResumeDBTable.Arn
