AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '

  SAM Template for cloud-resume-backend

  '
Globals:
  Api:
    OpenApiVersion: 3.0.1
Resources:
  MyResumeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyResumeApi
      StageName: prod
      Cors: '''*'''
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://codeandtechresume.com/70e1f320cc17c78f83ce106b8e06ac63
  ResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://codeandtechresume.com/dd48eaca2ac4f6db8c137486f7308b2f
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Policies:
      - AWSLambdaBasicExecutionRole
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          - dynamodb:BatchGetItem
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:BatchWriteItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - logs:CreateLogStream
          - logs:PutLogEvents
          - logs:CreateLogGroup
          Resource: '*'
  ResumeDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: siteUrl
        AttributeType: S
      KeySchema:
      - AttributeName: siteUrl
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: visitorcount
Outputs:
  ResumeApi:
    Description: API Gateway endpoint URL for Prod stage for Cloud Resume function
    Value:
      Fn::Sub: https://${MyResumeApi}.execute-api.${AWS::Region}.amazonaws.com/prod/count
  ResumeFunction:
    Description: Cloud Resume Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ResumeFunction
      - Arn
  ResumeFunctionIamRole:
    Description: Implicit IAM Role created for Cloud Resume function
    Value:
      Fn::GetAtt:
      - ResumeFunctionRole
      - Arn
  ResumeDBTable:
    Description: DynamoDB table to store the visitor count
    Value:
      Fn::GetAtt:
      - ResumeDBTable
      - Arn
