version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket codeandtechresume.com --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - output.yaml 