name: "Deploy cloud resume SAM template"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: falnyr/aws-sam-deploy-action@v1.0.0
      env:
        TEMPLATE: './src/template.yaml'
        AWS_STACK_NAME: cloud-resume
        AWS_REGION: 'us-east-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}