name: Cloud resume backend workflow
on:
  push:
    branches:
      - master
jobs:
  aws_sam:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: sam build
        uses: youyo/aws-sam-action/python3.8@master
        with:
          sam_command: package --template-file ./src/template.yaml --output-template-file output.yaml ${{ secrets.S3_BUCKET }} 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          STACK_NAME: ${{ secrets.STACK_NAME }}
          AWS_DEFAULT_REGION: us-east-2

      - name: sam deploy
        uses: youyo/aws-sam-action/python3.8@master
        with:
          sam_command: deploy --template-file output.yaml --stack-name ${{ secrets.STACK_NAME }} --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          STACK_NAME: ${{ secrets.STACK_NAME }}
          AWS_DEFAULT_REGION: us-east-2
