name: "Deploy SAM Stack to Production"
on:
  push:
    branches: [ master ]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: AWS IAM Assume Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: sam build
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: build -t ./src/template.yaml
    - name: sam deploy
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: |
          deploy \
            --template-file ./src/template.yaml \
            --stack-name cloud-resume \
            --s3-bucket ${{ S3_BUCKET }}\
            --region us-east-2 \
            --capabilities CAPABILITY_IAM
